# Generated by Django 5.1.4 on 2024-12-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='daily_changes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='monthly_changes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='weekly_changes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
