# Generated by Django 5.1.4 on 2024-12-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_notificationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='user_mail',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Почта пользователя'),
        ),
    ]
