# Generated by Django 5.1.4 on 2024-12-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_alter_notificationsettings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='notification_period',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='notification_types',
            field=models.CharField(max_length=20),
        ),
    ]
