# Generated by Django 5.1.4 on 2024-12-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_alter_notificationsettings_notification_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='daily_changes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='monthly_changes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='weekly_changes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='user_mail',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Почта пользователя'),
        ),
    ]
